function out1 = o_Htm_BASE_fcn(in1)
%o_Htm_BASE_fcn
%    OUT1 = o_Htm_BASE_fcn(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    28-Feb-2024 16:42:57

alpha = in1(4,:);
beta = in1(5,:);
gamma = in1(6,:);
x = in1(1,:);
y = in1(2,:);
z = in1(3,:);
t2 = cos(alpha);
t3 = cos(beta);
t4 = cos(gamma);
t5 = sin(alpha);
t6 = sin(beta);
t7 = sin(gamma);
out1 = reshape([t3.*t4,t2.*t7+t4.*t5.*t6,t5.*t7-t2.*t4.*t6,-t3.*t7,t2.*t4-t5.*t6.*t7,t4.*t5+t2.*t6.*t7,t6,-t3.*t5,t2.*t3,x,y,z],[3,4]);
