function p_J_q = p_J_q_fcn(in1)
%P_J_Q_FCN
%    P_J_Q = P_J_Q_FCN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Feb-2025 22:07:23

alpha = in1(4,:);
beta = in1(5,:);
gamma = in1(6,:);
x = in1(1,:);
y = in1(2,:);
z = in1(3,:);
t2 = sin(beta);
t3 = sin(gamma);
t4 = cos(beta);
t5 = cos(gamma);
t6 = sin(alpha);
t7 = cos(alpha);
t8 = t5.*t7;
t15 = t2.*t3.*t6;
t9 = t8-t15;
t10 = t2.*t5.*t7;
t14 = t3.*t6;
t11 = t10-t14;
t12 = t3.*t7;
t13 = t2.*t5.*t6;
t16 = t5.*t6;
t17 = t2.*t3.*t7;
t18 = t2.*x;
t19 = t4.*t7.*z;
t20 = t18+t19-t4.*t6.*y;
p_J_q = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t4.*t5,t3.*t4,-t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t12-t13,-t8+t15,t4.*t6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t11,-t16-t17,-t4.*t7,0.0,0.0,0.0,t11,-t5.*t6-t2.*t3.*t7,-t4.*t7,t12+t13,t9,-t4.*t6,t3.*t6.*y-t3.*t7.*z-t2.*t5.*t7.*y-t2.*t5.*t6.*z,t5.*t6.*y-t5.*t7.*z+t2.*t3.*t7.*y+t2.*t3.*t6.*z,t4.*(t7.*y+t6.*z),-t2.*t5,t2.*t3,t4,t4.*t5.*t6,-t3.*t4.*t6,t2.*t6,-t4.*t5.*t7,t3.*t4.*t7,-t2.*t7,t5.*t20,-t3.*t20,-t4.*x-t2.*t6.*y+t2.*t7.*z,-t3.*t4,-t4.*t5,0.0,t9,-t3.*t7-t2.*t5.*t6,0.0,t16+t17,t11,0.0,t3.*t4.*x-t5.*t7.*y-t5.*t6.*z+t2.*t3.*t6.*y-t2.*t3.*t7.*z,t4.*t5.*x+t3.*t7.*y+t3.*t6.*z+t2.*t5.*t6.*y-t2.*t5.*t7.*z,0.0],[12,6]);
