function V_Grav = V_Grav(in1)
%V_Grav
%    V_Grav = V_Grav(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    28-Feb-2024 16:45:39

q_3 = in1(3,:);
q_4 = in1(4,:);
q_5 = in1(5,:);
q_6 = in1(6,:);
t2 = cos(q_4);
t3 = cos(q_6);
t4 = sin(q_4);
t5 = sin(q_5);
t6 = sin(q_6);
et1 = q_3.*5.16868608996e+1;
et2 = t3.*t4.*2.9012642044479e-3;
et3 = t4.*t6.*1.114482940821058e-2;
et4 = t2.*cos(q_5).*(-1.010094396402024);
et5 = t2.*t3.*t5.*(-1.114482940821058e-2);
et6 = t2.*t5.*t6.*2.9012642044479e-3;
V_Grav = et1+et2+et3+et4+et5+et6;
